backend/Dockerfile
backend/install.sh
docker-compose.yml

Update backend Dockerfile to a good state. Related to https://github.com/ecmwf/forecast-in-a-box/issues/11

Update backend Dockerfile

---

backend/forecastbox/api/routers/job.py
backend/forecastbox/api/routers/product.py
backend/forecastbox/config.py
backend/forecastbox/models/model.py
backend/forecastbox/products/plots/__init__.py
backend/forecastbox/products/plots/maps.py
backend/forecastbox/products/standard.py
backend/pyproject.toml
frontend/src/pages/jobs/progress.tsx
frontend/src/pages/result/result.tsx

[backend] fix: Product Updates

---

backend/forecastbox/products/plots/maps.py

Conditional imports cannot be used as top-level function annotations, otherwise it crashes

[backend.products] make imports correctly conditional

---

frontend/src/pages/Status.tsx

[frontend] Add webmars status

---

backend/forecastbox/api/execution.py
backend/forecastbox/api/routers/job.py
backend/forecastbox/api/routers/model.py
backend/forecastbox/db/__init__.py
backend/forecastbox/db/job.py
backend/forecastbox/db/model.py
backend/forecastbox/entrypoint.py
backend/forecastbox/schemas/model.py
backend/pyproject.toml
backend/tests/integration/conftest.py
backend/tests/integration/test_admin_flows.py
backend/tests/integration/test_model.py
backend/tests/integration/test_submit_job.py

removes mongodb altogether, as no usage remains
I still need to remove it from docker compose files -- I'll clean them up once I look at the frontend

[backend] refactor model edit/download to sqlite

---

frontend/src/components/jobs/progress.tsx
frontend/src/pages/QuickLaunch.tsx

Quick launch wasnt' counting correctly

[frontend] fix: quick launch

---

backend/forecastbox/api/routers/gateway.py
frontend/src/pages/admin/gateway.tsx

Gateway isn't streaming logs to the frontend

[backend] fix: gateway

---

backend/forecastbox/api/routers/auth.py
backend/forecastbox/auth/oidc.py
backend/forecastbox/auth/users.py
backend/forecastbox/config.py
backend/forecastbox/entrypoint.py
backend/tests/integration/conftest.py
backend/tests/integration/test_admin_flows.py
backend/tests/integration/test_model.py
backend/tests/integration/test_submit_job.py
backend/tests/integration/utils.py
frontend/src/api.ts
frontend/src/layouts/AdminPage.tsx
frontend/src/layouts/LoggedIn.tsx
frontend/src/layouts/MainLayout.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/oidcCallback.tsx

[auth] Update to oidc

---

.github/workflows/cd.yml

[cicd] var name typo

---

backend/DockerfileMARSRocky
cascade/DockerfileMARSRocky

Update Mars based images to use prebuilt rocky containers

[cicd] Update MARS Images

---

.github/workflows/build-containers-eccr.yml
.github/workflows/build-containers-ghcr.yml
backend/Dockerfile
backend/DockerfileMARSRocky
backend/install.sh
backend/pyproject.toml
cascade/Dockerfile
cascade/DockerfileMARSRocky
cascade/install.sh
docker-compose-ewc.yml
docker-compose.yml

[cicd] Update compose

---

backend/pyproject.toml

0.4.0 just released https://github.com/ecmwf/earthkit-workflows/actions/runs/16522567670/job/46727623269

chore: bump ekw version

---

backend/forecastbox/api/routers/model.py
backend/forecastbox/db/core.py
backend/forecastbox/db/model.py
backend/forecastbox/entrypoint.py
backend/forecastbox/standalone/entrypoint.py
backend/pyproject.toml
backend/scripts/bigtest.py

1/ eliminate one very annoying logging kind
2/ relax timeouts for big script
3/ flush the progressing-downloads db on start

[backend] relax timeouts in bigscript, reduce logging

---

backend/forecastbox/standalone/entrypoint.py

we increase attempt count because macos was recently changed to spawn and thus got slower
we fix a bug that when the startup check failed, the entrypoint script failed, but the server was kept running, possibly without gateway having started. Instead, the startup check failure now stops the server as well

[backend] fix wait for start

---

backend/forecastbox/models/metadata.py
backend/forecastbox/products/export.py
backend/forecastbox/products/plots/maps.py

Fix netcdf export issues
Closes #106 

fix: Address netcdf issue

---

frontend/src/pages/QuickLaunch.tsx

Sadly disable fireworks @havardf

chore: [frontend] Disable fireworks

---

backend/pyproject.toml

chore: Update compiled stack version

---

scripts/fiab.sh

- dont start the app when --warmup is given
- mark the --offline mode as not supported

[fiab.sh] fixes to startup

---

backend/forecastbox/models/nested.py

fix: Plugins version incompatabilities

---

backend/forecastbox/products/plots/maps.py

feat: Allow arbitrary domain in map

---

backend/forecastbox/api/utils.py

Stop stripping .* from checkpoint name

fix: Stop stripping .* from checkpoint name

---

backend/forecastbox/api/execution.py
backend/forecastbox/models/metadata.py
backend/forecastbox/models/model.py
backend/forecastbox/products/plots/maps.py

Updates for larger models
- Adjust env var propogation
- Fix package extraction

fix: Updates for larger models

---

backend/forecastbox/products/plots/maps.py

General fix ups due to recent PR's in the map product

fix: Updates to maps

---

backend/forecastbox/models/model.py

Fixes to improve metadata when running ensembles

fix: Allow for None in ensemble graph

---

backend/forecastbox/api/execution.py
backend/forecastbox/api/routers/admin.py
backend/forecastbox/api/routers/execution.py
backend/forecastbox/api/routers/job.py
backend/forecastbox/config.py
backend/forecastbox/models/globe.py
backend/forecastbox/models/metadata.py
backend/forecastbox/models/model.py
backend/forecastbox/models/nested.py
backend/forecastbox/products/plots/maps.py
backend/forecastbox/products/pproc.py
backend/forecastbox/products/standard.py
backend/forecastbox/rjsf/__init__.py
backend/forecastbox/rjsf/forms.py
backend/forecastbox/rjsf/from_pydantic.py
backend/forecastbox/rjsf/jsonSchema.py
backend/forecastbox/rjsf/utils.py
backend/forecastbox/standalone/entrypoint.py
backend/pyproject.toml
backend/tests/integration/test_submit_job.py
backend/tests/unit/rjsf/test_forms.py
backend/tests/unit/rjsf/test_from_pydantic.py
backend/tests/unit/rjsf/test_utils.py
frontend/src/components/graph_visualiser.tsx
frontend/src/pages/admin/settings.tsx

Move to rjsf for admin settings
Also add config saving

feat: [settings, rjsf] Update settings to use rjsf

---

backend/forecastbox/config.py
backend/forecastbox/products/plots/maps.py

Allow for '@' in plots schema for specification of where to install from

feat: Allow plots schema to include "@" for install path

---

backend/forecastbox/models/model.py
backend/forecastbox/products/ensemble/base.py
backend/forecastbox/products/pproc.py
backend/forecastbox/products/thermal.py

Sometimes pproc imports fail due to API/ABI issues,
Catch the error on import, and lock out pproc products if so

fix: Catch errors on import of pproc

---

backend/forecastbox/api/routers/job.py
backend/tests/integration/test_submit_job.py
frontend/src/components/results/Result.tsx
frontend/src/pages/jobs/status.tsx

Add filtering to jobs api and improve typing

feat: Add filtering to jobs api
